# Generated by Django 5.2.17 on 2026-09-13 18:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('INTERNSHIP', 'Internship'), ('RESEARCH', 'Research'), ('VOLUNTEER', 'Volunteer'), ('PART_TIME', 'Part-Time'), ('FULL_TIME', 'Full-Time'), ('FREELANCE', 'Freelance'), ('ORGANIZATIONAL', 'Organizational')], default='FULL_TIME', max_length=20),
        ),
    ]
