# Generated by Django 5.2.17 on 2026-09-20 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20260920_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=255)),
                ('award_url', models.URLField(blank=True)),
                ('award_image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
