# Generated by Django 5.2.17 on 2026-09-14 11:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_experience_ended_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='is_ongoing',
        ),
        migrations.AddField(
            model_name='experience',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('INTERNSHIP', 'Internship'), ('RESEARCH', 'Research'), ('VOLUNTEER', 'Volunteer'), ('PART_TIME', 'Part-Time'), ('FULL_TIME', 'Full-Time'), ('FREELANCE', 'Freelance'), ('ORGANIZATIONAL', 'Organizational')], default='FULL_TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
