# Generated by Django 5.2.17 on 2026-09-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_image_experience_thumbnail_and_more'),
    ]

    operations = [
    ]
