# Generated by Django 5.2.17 on 2026-09-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='education',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='education',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance')], default='full-time', max_length=20),
        ),
    ]
