# Generated by Django 5.2.17 on 2026-09-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_project_remove_education_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
